name: iOS Build Driver

on:
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Driver App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        working-directory: volta-driver
        run: npm install

      - name: Build iOS App locally on macOS Runner
        working-directory: volta-driver
        run: eas build --platform ios --profile preview --local --non-interactive --output Driver-iOS.tar.gz

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Driver-iOS-Build
          path: volta-driver/Driver-iOS.tar.gz
