name: iOS Build Driver

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Driver App
    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: Vn6hHQ1cb4AF0iNdANOmlb5oGSMZ7zFYFy4jdaKy

      - name: Select Xcode 16.1
        run: sudo xcode-select -s /Applications/Xcode_16.1.app/Contents/Developer

      - name: Install dependencies
        working-directory: volta-driver
        run: npm install

      - name: Build iOS App locally on macOS Runner
        working-directory: volta-driver
        run: EXPO_NO_DOCTOR=true eas build --platform ios --profile production --local --non-interactive --auto-submit --output Driver-iOS.ipa

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Driver-iOS-Build
          path: volta-driver/Driver-iOS.ipa
