name: Build iOS Customer App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: Vn6hHQ1cb4AF0iNdANOmlb5oGSMZ7zFYFy4jdaKy

      - name: Setup Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.1'

      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS

      - name: Install dependencies
        working-directory: volta-customer
        run: npm install

      - name: Build iOS App locally on macOS Runner
        working-directory: volta-customer
        run: EAS_BUILD_DISABLE_DOCTOR=1 eas build --platform ios --profile production --local --non-interactive --verbose-logs --output Customer-iOS.ipa

      - name: Dump xcodebuild logs on failure
        if: failure()
        run: |
          cat ~/Library/Logs/gym/*.log > xcodelog.txt || true
          curl -T xcodelog.txt https://transfer.sh/customer-xcodelog.txt > url.txt || true
          cat url.txt || true
          cat xcodelog.txt | tail -n 1000 || true

      - name: Submit iOS App to TestFlight
        working-directory: volta-customer
        run: eas submit --platform ios --profile production --path Customer-iOS.ipa --non-interactive
