name: iOS Build Customer

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    name: Build iOS Customer App
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: Vn6hHQ1cb4AF0iNdANOmlb5oGSMZ7zFYFy4jdaKy

      - name: Install dependencies
        working-directory: volta-customer
        run: npm install

      - name: Build iOS App locally on macOS Runner
        working-directory: volta-customer
        run: eas build --platform ios --profile production --local --non-interactive --auto-submit --output Customer-iOS.ipa

      - name: Upload iOS Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Customer-iOS-Build
          path: volta-customer/Customer-iOS.ipa
